### ISSUE TITLE
说明

### ISSUE THREAD

**Issue by JMike2** [Timber-Ye/quants#9]
文件hybird_order.py表示混合策略 funding表示融资金额 lever表示杠杆倍数,具体策略如下：
因为macd和bolling指标回测表现较好，所以macd信号和bolling信号权重都为0.43，trix略差，权重为0.14
   signal=0.43*macd.value +0.43*bolling.value +0.14*trix.value
   当信号>=0.86，就是macd和bolling都提示买入，trix没有卖出信号时，混合策略为杠杆买入信号，两倍杠杆买入
   当0.86>信号>=0.43, 就是macd和bolling其中一个提示买入，或者都为买入但trix为卖出时，全仓买入
   当0.43>信号>=0，为持有信号，不做操作
   当0>信号>-0.86,macd和bolling其中一个提示卖出，或者都为卖出但trix为买入时，全仓卖出
   当信号<-0.86,当macd和bolling都提示卖出，并且trix没有买入信号时，为做空信号，全仓开空
最后收益率为127.94%，超过指数本身25.91%的涨幅，最大回撤为79%，夏普比率为0.44，年化收益率8.04%

**Comment by Timber-Ye** [comment]
此Issue已迁移至[PR](https://github.com/Timber-Ye/quants/pull/10)
